id = "bbc"
name = "BBC"

[shared.discovery.default]
type = "html"

[[shared.discovery.default.html.link_selectors]]
link = "a"

[shared.transformation.default]
[[shared.transformation.default.replace]]
field = "title"
pattern = " - BBC News .*$"
replacement = ""
regex = true
case_sensitive = false

[[languages]]
language = "en"
max_items = 5
shared = "default"

[languages.discovery]
url = "https://www.bbc.com/news/topics/cywd23g0gxgt"

[[languages.discovery.html.url_rules]]
type = "filter_prefix"
value = "/news/articles/"

[[languages.discovery.html.url_rules]]
type = "prepend"
value = "https://www.bbc.com"
condition = "if_relative"

[[languages]]
language = "si"
max_items = 5
shared = "default"

[languages.discovery]
url = "https://www.bbc.com/sinhala/topics/cg7267dz901t"

[[languages.discovery.html.url_rules]]
type = "filter_prefix"
value = "https://www.bbc.com/sinhala/articles/"

[[languages]]
language = "ta"
max_items = 5
shared = "default"

[languages.discovery]
url = "https://www.bbc.com/tamil/topics/cz74k7p3qw7t"

[[languages.discovery.html.url_rules]]
type = "filter_prefix"
value = "https://www.bbc.com/tamil/articles/"
