name = "Daily Mirror"

[title_transform]
skip = [
    { contains = "An Error Was", case_sensitive = false }
]

replace = [
    { pattern = " - Breaking News | Daily Mirror", with = "", case_sensitive = false }
]

[[languages]]
language = "en"
max_items = 5

[languages.listing]
type = "rss"
url = "https://www.dailymirror.lk/rss/todays_headlines/419"

[languages.article]
browser = true
