id = "divaina"
name = "Divaina"

[[languages]]
language = "si"
max_items = 5

[languages.discovery]
type = "html"
url = "https://www.divaina.lk/category/breaking-news"

[languages.discovery.html]
link_selectors = ["a.p-url"]

[[languages.discovery.html.url_rules]]
type = "filter_prefix"
value = "https://www.divaina.lk/"
