id = "gagana"
name = "Gagana"

[[languages]]
language = "si"
max_items = 5

[languages.discovery]
type = "html"
url = "https://gagana.lk/news/srilanka"

[languages.discovery.html]
link_selectors = ["div.a-item h4 a"]

[[languages.discovery.html.url_rules]]
type = "filter_prefix"
value = "https://gagana.lk/article/"

[[languages.discovery.html.url_rules]]
type = "prepend"
value = "https://gagana.lk"
condition = "if_relative"
