name = "Hiru News"

[[languages]]
language = "si"
max_items = 5

[languages.listing]
type = "html"
url = "https://www.hirunews.lk"
selectors = ["a.card-featured", "a.card-v1"]
url_prefix = "https://hirunews.lk/"

[[languages]]
language = "en"
max_items = 5

[languages.listing]
type = "html"
url = "https://www.hirunews.lk/en/"
selectors = ["a.card-featured", "a.card-v1"]
url_prefix = "https://hirunews.lk/"

[[languages]]
language = "ta"
max_items = 5

[languages.listing]
type = "html"
url = "https://www.hirunews.lk/tm/"
selectors = ["a.card-featured", "a.card-v1"]
url_prefix = "https://hirunews.lk/"
