name = "The Island"

[[languages]]
language = "en"
max_items = 5

[languages.discovery]
type = "rss"
url = "https://island.lk/feed/"

[languages.extraction]
browser = true

[languages.extraction.content]
scope_selector = ".mvp-post-soc-out.right.relative"
