id = "lankapuvath"
name = "Lankapuvath"

[[languages]]
language = "en"
max_items = 5

[languages.discovery]
type = "rss"
url = "https://english.lankapuvath.lk/feed/"

[languages.transformation]
[[languages.transformation.replace]]
field = "body"
pattern = "^\\(LANKAPUVATH \\| COLOMBO\\) – "
replacement = ""
regex = true

[[languages]]
language = "si"
max_items = 5

[languages.discovery]
type = "rss"
url = "https://sinhala.lankapuvath.lk/feed/"

[languages.transformation]
[[languages.transformation.replace]]
field = "body"
pattern = "^\\(කොළඹ \\| ලංකාපුවත්\\) – "
replacement = ""
regex = true
