id = "news-lk"
name = "News.lk"

[shared.discovery.default]
type = "html"
browser = true

[[shared.discovery.default.html.link_selectors]]
link = "article.item h2 a"

[[shared.discovery.default.html.url_rules]]
type = "filter_prefix"
value = "/news/"

[shared.extraction.default]
browser = true

[shared.validation.default]
[[shared.validation.default.require]]
field = "body"
type = "min_length"
value = "200"

[[languages]]
language = "en"
max_items = 2
shared = "default"

[languages.discovery]
url = "https://news.lk/news/"

[[languages.discovery.html.url_rules]]
type = "prepend"
value = "https://news.lk"
condition = "if_relative"

[[languages]]
language = "si"
max_items = 2
shared = "default"

[languages.discovery]
url = "https://sinhala.news.lk/news/"

[[languages.discovery.html.url_rules]]
type = "prepend"
value = "https://sinhala.news.lk"
condition = "if_relative"

[[languages]]
language = "ta"
max_items = 2
shared = "default"

[languages.discovery]
url = "https://tamil.news.lk/news/"

[[languages.discovery.html.url_rules]]
type = "prepend"
value = "https://tamil.news.lk"
condition = "if_relative"
